# Generated by Django 4.1.1 on 2022-09-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="associates",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="image",
            name="category",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="image",
            name="hashtags",
            field=models.TextField(),
        ),
    ]
