# Generated by Django 4.1.1 on 2022-09-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0002_alter_image_associates_alter_image_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]
